#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#

# amqp provider, default value: rabbitmq.
amqp.provider=rabbitmq
# RabbitMQ Specific
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=xpanse
spring.rabbitmq.password=Xpanse@2023
# springwolf AsyncAPI
springwolf.enabled=true
# AsyncAPI Docket
springwolf.docket.info.title=Terraform Async Request APIs
springwolf.docket.info.version=@project.version@
springwolf.docket.info.description=Terraform Async Request APIs
springwolf.docket.base-package=org.eclipse.xpanse.terra.boot.api.queue
springwolf.docket.servers.amqp-server.protocol=amqp
springwolf.docket.servers.amqp-server.host=${spring.rabbitmq.host}:${spring.rabbitmq.port}
springwolf.plugin.amqp.publishing.enabled=true